### ISSUE TITLE
0.9.0 compatibility

### ISSUE THREAD

**Issue by ryw** [Differential/accounts-entry#243]
it's been reported on meteor-core that we're not 0.9.0 compatible

**Comment by RanaivosonHerimanitra** [comment]
I have just upgraded to meteor 1.2 then I got this error:
```
Changes to your project's package version selections:
                                              
joshowens:accounts-entry  added, version 0.7.3

                                              
joshowens:accounts-entry: INCOMPATIBLE WITH METEOR 0.9.0 OR LATER
```
Do you know how to fix it?

**Comment by Deuce15** [comment]
using meteor 1.2 and i got this error from my terminal:
The package joshowens:accounts-entry at 0.7.3 is incompatible with Meteor 0.9.0 or later. 
I've tried to solve it but it isn't working.
Somebody help me

**Comment by AhmedHamedTN** [comment]
SOLVED

i was looking for this issue. i am running Meteor 1.2 and i found this on Stackoverflow.

## **For Meteor 1.2.0.1 version the following should work:

meteor add check

meteor add selaias:accounts-entry**

here is the git repo : [`Selaias`](https://github.com/selaias/accounts-entry)

**Comment by Mrkezii** [comment]
thanks @AhmedHamedTN your solution seems to work
