### ISSUE TITLE
Couldn't find a template named "EntrySignOut"

### ISSUE THREAD

**Issue by frabrunelle** [Differential/accounts-entry#333]
When I go to /sign-out, I briefly see the following error message in red:

```Couldn't find a template named "EntrySignOut" or "entrySignOut". Are you sure you defined it?```

The message is shown only a fraction of a second so I had to record my screen to be able to read it. It's distracting and I would like to remove it.

Can anyone reproduce this? And do you know how to remove the error message?

Thank you very much.

**Comment by funkyeah** [comment]
I think it has to do with:

/shared/router.coffee

    @route 'entrySignOut',
      path: '/sign-out'
      onBeforeAction: ()->
        Session.set('entryError', undefined)
        if AccountsEntry.settings.homeRoute
          Meteor.logout () ->
            Router.go AccountsEntry.settings.homeRoute
        @next()

Because Router.go is only done as a callback to Meteor.logout, iron proceeds and tries to find the template for entrySignOut until that callback is called

probably need to either render a loading template or just not call @next() which could have its own problems

**Comment by lukeclifton** [comment]
+1

**Comment by SeabookChen** [comment]
need to patch his code, using the following code.
'''
@route 'entrySignOut',
    path: '/sign-out'
    onBeforeAction: ()->
      Session.set('entryError', undefined)
      if not AccountsEntry.settings.homeRoute
        @next()
      else
        Meteor.logout () ->
          Router.go AccountsEntry.settings.homeRoute
'''

**Comment by cunneen** [comment]
Can this be marked as fixed? 
/cc @fix

**Comment by fix** [comment]
Yes i merged your PR about it

**Comment by almogdesign** [comment]
I see this is merged  but has their been an updated release? I'm not seeing a new version?

**Comment by fix** [comment]
Sorry, I have not yet stabilized the new version. Also I do not have access to the Differential repo in meteor.

**Comment by almogdesign** [comment]
I think might be good to fork and take over this, it seems that they haven't updated for sometime. I will do the fix on my end for now

**Comment by fungilation** [comment]
@queso? Instead of fragmenting efforts, adding someone who can push new version on git to update the Meteor package would be nice.

**Comment by ryw** [comment]
hi guys - we're definitely open to adding maintainers to the project. I don't think anyone is actively using accounts-entry at Differential at the moment, which is why we've not been very involved lately.

I'm curious why you guys are still going w/ this package vs. [useraccounts](https://github.com/meteor-useraccounts).

**Comment by fix** [comment]
Well, that is a bit tricky to say, but i did not know about useraccounts...

**Comment by fungilation** [comment]
Ya, didn't know about useraccounts either. Looks good, as replacement?

**Comment by ryw** [comment]
Yeah they started with accounts-entry and have built additional stuff on top, much more actively developed.

**Comment by almogdesign** [comment]
Yea I also didn't know about useraccounts I guess this is the direction

**Comment by cunneen** [comment]
In my case, it will take a while to migrate. Accounts-entry generally works
well, we've been using it for a while and switching packages is not highest
priority at the moment (although we will do it eventually).

**Comment by fungilation** [comment]
@cunneen same here
