### ISSUE TITLE
Configure fb button stays open

### ISSUE THREAD

**Issue by justindra** [Differential/accounts-entry#339]
Hi,

So I've just noticed that when I load the sign-in page, the page first loads with the configure facebook button. Which then disappears to turn into the "sign in with facebook".

Just wondering if I can disable this so that my users would not be faced with a configure button, but just hides the sign in button until the app knows that the fb login is available.

Cheers!

**Comment by fix** [comment]
Are you using the last version of meteor?

**Comment by justindra** [comment]
Hi,

Yes I am.

Cheers,

Justin

**Comment by rubenlpz** [comment]
@justindra Did you find any solution for this?  The same is happening to me, the configure facebook button is shown for 10-20 seconds after switch to login with facebook button.

**Comment by rubenlpz** [comment]
Solution:
Wait until the function Accounts.loginServicesConfigured() returns "true".  After that you can show the login facebook button.  You can call this function like this:

Meteor.autorun(function () {
  if (Accounts.loginServicesConfigured()) {
// Show "Sign in with FB" button or show the entire login template
  } 
}); 

You can also add a else which will shown a loading template.

**Comment by justindra** [comment]
Yep, sorry I forgot to close this. But yep I used a similar solution to that.
