### ISSUE TITLE
Cryptic errors on Meteor 1.0.3.1.

### ISSUE THREAD

**Issue by nicksergeant** [Differential/accounts-entry#344]
Created a brand new project and adding this package blows up upon installation:

1. `meteor create siftie`
2. `cd siftie`
3. `mrt add accounts-entry`
4. `meteor`

Errors:

![http://i.imgur.com/JdBCoKM.png](http://i.imgur.com/JdBCoKM.png)

**Comment by fix** [comment]
you need to add the `account-password` package

**Comment by nicksergeant** [comment]
Ah. K. Different errors after installing that:

![http://i.imgur.com/Vs8OCKD.png](http://i.imgur.com/Vs8OCKD.png)

**Comment by fix** [comment]
Well, can't reproduce, are you sure you have last version of meteor, perform a `meteor update`and let me know.

**Comment by nicksergeant** [comment]
I'm on `Meteor 1.0.3.1`. Here's a screencast showing the entire process:

![http://i.imgur.com/dcYiB7l.gif](http://i.imgur.com/dcYiB7l.gif)

**Comment by fix** [comment]
Ahah, well done you spotted it, you should run the command `joshowens:accounts-entry`
I was doing it automatically
Updating the README. Sorry for that.

**Comment by nicksergeant** [comment]
Ah, sorry I forgot to respond here - that fixed command was what I needed. Thanks, @fix!
