### ISSUE TITLE
 Exception while invoking method 'forgotPassword' Error: No such email for user.

### ISSUE THREAD

**Issue by almogdesign** [Differential/accounts-entry#354]
I'm the following error my the user email is correct checked via the DB 

Exception while invoking method 'forgotPassword' Error: No such email for user.
I20150219-16:59:21.460(2)?     at Object.Accounts.sendResetPasswordEmail (packages/accounts-password/password_server.js:380:1)
I20150219-16:59:21.460(2)?     at [object Object].Meteor.methods.forgotPassword (packages/accounts-password/password_server.js:358:1)
I20150219-16:59:21.460(2)?     at packages/check/match.js:109:1
I20150219-16:59:21.460(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150219-16:59:21.461(2)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20150219-16:59:21.461(2)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1596:1)
I20150219-16:59:21.461(2)?     at packages/ddp/livedata_server.js:648:1
I20150219-16:59:21.461(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150219-16:59:21.461(2)?     at packages/ddp/livedata_server.js:647:1
I20150219-16:59:21.461(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)

**Comment by fix** [comment]
Looking at the stacktrace, it sounds linked to the account-password package, handling the email match. Try to check on the package issue lisy

**Comment by almogdesign** [comment]
@fix yes your right but the accounts entry package is taking the value from the input field and using it for the forgot password. 

I think the issue is that it's either send a empty value or the wrong value?

**Comment by almogdesign** [comment]
Issue on my end I was overriding the address array and saving it as an object
