### ISSUE TITLE
signInAfterRegistration doesn't work 

### ISSUE THREAD

**Issue by outaTiME** [Differential/accounts-entry#371]
Guys, here again ... switching the config flag `signInAfterRegistration` does nothing, i suppose when its false it must be go to `verification-pending` right ?

thks !

**Comment by outaTiME** [comment]
Probably something related with #370, im coding something bad ??

**Comment by outaTiME** [comment]
These features are not yet released ??

**Comment by queso** [comment]
I would recommend you check out UserAccounts packaging instead of accounts-entry.

**Comment by outaTiME** [comment]
Why, im already using this package ?! Its better ?!

**Comment by queso** [comment]
This package is no longer being maintained or supported.


--Josh Owens | 513-678-7081 | http://joshowens.me | @joshowens

**Comment by outaTiME** [comment]
oups, thks pal i give a try ...
